platform :ios, '16.0'
use_frameworks!

target 'DrowsyDriver' do
  # Use ML Kit Face Detection to mirror Android
  pod 'GoogleMLKit/FaceDetection'
  # RevenueCat for purchases parity
  pod 'RevenueCat'
end
